version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - noxone
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-plugin
    versions:
    - 1.4.21-2
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-js
    versions:
    - 1.4.21-2
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-serialization
    versions:
    - 1.4.21-2
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlinx:kotlinx-serialization-core-js
    versions:
    - 1.1.0
  - dependency-name: org.jetbrains.kotlinx:kotlinx-serialization-json-js
    versions:
    - 1.1.0
